spring:
  config:
    activate:
      on-profile: test
environment: test
server:
  port: 4000

VarTree:
  welcomeMsg: Hello from test

---
spring:
  config:
    activate:
      on-profile: prod
environment: prod
server:
  port: 5000
VarTree:
  welcomeMsg: Hello from prod